#include "boost_class_exports.h"

BOOST_CLASS_EXPORT_IMPLEMENT(taets::FloatSeries)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::ImageSeries)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::Color)

BOOST_CLASS_EXPORT_IMPLEMENT(taets::InputConnector<taets::FloatSeries>)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::InputConnector<taets::ImageSeries>)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::OutputConnector<taets::FloatSeries>)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::OutputConnector<taets::ImageSeries>)

BOOST_CLASS_EXPORT_IMPLEMENT(taets::ColorSetting)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::ChoiceSetting)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::FileSetting)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::NumberSetting)

BOOST_CLASS_EXPORT_IMPLEMENT(taets::NumberParam)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::FileParam)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::ChoiceParam)

BOOST_CLASS_EXPORT_IMPLEMENT(taets::InspectorNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::ConstantNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::ColorNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::MixNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::TransformNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::VideoInputNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::GradientInputNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::BlurNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::BrightnessContrastNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::PSNRNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::NoiseInputNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::SharpenNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::ImageInputNode)
BOOST_CLASS_EXPORT_IMPLEMENT(taets::BinaryNode)
